### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by huangyuanf** [astrazeneca-cgr-publications/PEACOK#3]
when I have installed all dependencies,but I could not install PEACOK :
Warning message:
package ‘PEACOK’ is not available (for R version 3.6.1)

Thank you

**Comment by 1emmy** [comment]
> 当我安装了所有依赖项，但无法安装 PEACOK 时： 警告消息： 包“PEACOK”不可用（对于 R 版本 3.6.1）
> 
> 谢谢
I have the same problem. How did you solve it
Thank you

**Comment by QuanliWang** [comment]
Could you please post the command and sessionInfo() output when you install the package?

**Comment by 1emmy** [comment]
> Could you please post the command and sessionInfo() output when you install the package?
I'm sorry to bother you, but I've already solved the problem. Thank you very much for replying to your question.
